[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge_contract = "1TetRib49XZYuKBypgVao4JoTSKJYgtmnNCp4P132pp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
